### ISSUE TITLE
alignement bizarre sur la page index dans certaines résolutions

### ISSUE THREAD

**Issue by ahoy-jon** [ScalaIO/scala.io#63]
<img width="1380" alt="image" src="https://github.com/ScalaIO/scala.io/assets/83247/beb69a2a-afa2-42ec-924c-cb6300707d3e">

de toutes les façons, la régle c'est d'aligner toujours à gauche, sauf exception

**Comment by iusildra** [comment]
J'ai enfin trouvé comment avoir l'alignement à gauche en conservant un "centrage" (sur certaines résolutions les espaces à gauche/droite ce n'étaient pas équilibrés)
Merci copilot :joy:
