### ISSUE TITLE
Rajouter @LambdaNantes dans les partenaires communautaires

### ISSUE THREAD

**Issue by ahoy-jon** [ScalaIO/scala.io#94]
@xvw il y a un logo ? https://mobilizon.fr/@lambdanantes

**Comment by xvw** [comment]
A part le ridicule qui dit "muehehe"... Non

**Comment by iusildra** [comment]
Il est très bien le `muehehe` :joy:

**Comment by ahoy-jon** [comment]
Ok, vous l'avez en haute définition ? C'est pour afficher dans un stade

**Comment by xvw** [comment]
Outch, c'est pour quand ?

Le ven. 26 janv. 2024, 13:37, Jonathan Winandy ***@***.***> a
écrit :

**Comment by ahoy-jon** [comment]
3 février, 21h à la Beaujoire

**Comment by iusildra** [comment]
Sinon on peut toujours utiliser une IA pour l'upscale

**Comment by ahoy-jon** [comment]
on n'a pas besoin de upscale (désolé pour l'humour)



Le ven. 26 janv. 2024 à 14:06, Lucas Nouguier ***@***.***> a
écrit :
